// demo_output_react.jsx
import React from 'react';
import './styles.css';

const GeneratedComponent = () => {
  return (
    <div className="container">
    <header className="header">Sample Header</header>
    <button className="button">Click Me</button>
    <p className="text">This is some sample text content</p>
    <input className="input" placeholder="Enter text here" />
    </div>
  );
};

export default GeneratedComponent;

// demo_output_vue.vue
<template>
  <div class="container">
    <header class="header">Sample Header</header>
    <button class="button">Click Me</button>
    <p class="text">This is some sample text content</p>
    <input class="input" placeholder="Enter text here" />
  </div>
</template>

<script>
export default {
  name: 'GeneratedComponent',
  data() {
    return {
      // Add component data here
    };
  },
  methods: {
    // Add component methods here
  }
};
</script>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 20px;
}

.header {
  background-color: #2196F3;
  color: white;
  padding: 16px;
  margin: 0;
}

.button {
  background-color: #4CAF50;
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 4px;
  cursor: pointer;
}

.text {
  color: #333333;
  font-size: 14px;
  margin: 0;
}

.input {
  border: 1px solid #CCCCCC;
  padding: 8px;
  border-radius: 4px;
  font-size: 14px;
}
</style>
